public interface InterfaceClass { // a interface pode ser implementada por outras classes, como a virtual e a abstract e para ser implementada você usa a palavra ( implements ) invez de extands
// e em uma classe interface tera somente a assinatura de métodos, e igual ao abstract a classe que sera implementada é obrigatorio a implementação dos métodos

    String nome();
    String sobrenome();
    Integer idade();
    String cpf();
}